[template]
src = "nslcd.conf.tmpl"
dest = "/etc/nslcd.conf"
keys = [
  "/ldap/uri",
  "/ldap/base",
  "/ldap/binddn",
  "/ldap/bindpw",
  "/ldap/filter",
  "/ldap/ssl/enable",
  "/ldap/ssl/cacertfile",
]